### ISSUE TITLE
error when run python main.py

### ISSUE THREAD

**Issue by lijie2160** [hpc203/scrfd-opencv#5]
Traceback (most recent call last):
  File "main.py", line 125, in <module>
    outimg = mynet.detect(srcimg)
  File "main.py", line 107, in detect
    i = i[0]
IndexError: invalid index to scalar variable.

**Comment by NickChang97** [comment]
> Traceback (most recent call last): File "main.py", line 125, in outimg = mynet.detect(srcimg) File "main.py", line 107, in detect i = i[0] IndexError: invalid index to scalar variable.


I also encounter the same error, do you solve it ? If yes, would you mind sharing the solution?

**Comment by NickChang97** [comment]
Just delete this line. It will work well
