### ISSUE TITLE
两个版本都有点报错，求助一下

### ISSUE THREAD

**Issue by Ma0zii** [hpc203/scrfd-opencv#8]
C++版本报错：
1>------ 已启动生成: 项目: ConsoleApplication2, 配置: Release x64 ------
1>main.obj : error LNK2001: 无法解析的外部符号 "void __cdecl cv::imshow(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class cv::_InputArray const &)" (?imshow@cv@@YAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV_InputArray@1@@Z)
1>已完成生成项目“ConsoleApplication2.vcxproj”的操作 - 失败。
========== 生成: 0 成功，1 失败，0 最新，0 已跳过 ==========
有9个无法解析符号的报错

python版本的报错：
Traceback (most recent call last):
  File "E:\karuizhi\scrfd-opencv-main\main.py", line 123, in <module>
    outimg = mynet.detect(srcimg)
  File "E:\karuizhi\scrfd-opencv-main\main.py", line 78, in detect
    bboxes = self.distance2bbox(anchor_centers, bbox_preds)
  File "E:\karuizhi\scrfd-opencv-main\main.py", line 35, in distance2bbox
    x1 = points[:, 0] - distance[:, 0]
ValueError: operands could not be broadcast together with shapes (12800,) (3200,)
这个相减维度不匹配x1 = points[:, 0] - distance[:, 0]

**Comment by lixueyuan123886** [comment]
我也是这个问题，请问解决了吗

**Comment by totalhuang** [comment]
> 我也是这个问题，请问解决了吗

python版本的问题我已经解决了，照着前面的issue里面的评论改的，这部分改成这样：
        for idx, stride in enumerate(self._feat_stride_fpn):
            scores = outs[idx][0]
            bbox_preds = outs[idx + self.fmc * 1][0] * stride
            kps_preds = outs[idx + self.fmc * 2][0] * stride
然后再运行，可能因为opencv版本的问题，我还需要去掉有一行 i = i[0]之后就可以正常运行了。
